eduardogmisiuk/dojot-verne

locust/README.md
locust/iot_device.py
locust/main.py
locust/mqtt_client.py
locust/requirements.txt
locust/utils.py

- Implements TSL
- Implements loop function of paho-mqtt
- Implements Locust class

Implements Locust and paho-mqtt

---

verne-webhooks/README.md
verne-webhooks/package-lock.json
verne-webhooks/package.json
verne-webhooks/routes/verneRoute.ts
verne-webhooks/src/app.ts
verne-webhooks/src/config.ts

Add corrections to log messages and creates the logging endpoints.

[verne-webhooks] Log endpoint

---

redisinit/cert.py
redisinit/generate_certs_for_broker.sh
redisinit/insert_things.py

closing connection for post

---

locust/README.md
locust/config.py
locust/log_controller.py
locust/main.py
locust/mqtt_client.py

Adds batch writing for log files and verifies whether there is connection with MQTT broker before publishing messages

Locust batch log

---

verne-webhooks/routes/verneRoute.ts

feature
The verne auth routine exausts (breaks) because it does not have a hook to parse the data
New hooks to parse the verne auth routine data
Nope
dojot/dojot#1266

Webhook with auth

---

kubernetes/ejbca_kube/ejbca_cluster.yaml
kubernetes/postgres_ejbca/postgres_service.yaml
kubernetes/postgres_ejbca/postgres_storage.yaml
kubernetes/postgres_ejbca/z_postgres_cluster.yaml
vernemq/docker-compose.yml

feature
EJBCA doesn't have persistence block, then, if the service breaks, all the data will be lost.
Now the persistence is made by an external postgres database. With this new feat, all the data is persisted and no more certificate creation delay exists (all data have index field, optmizing the certifcate search).
* **Is there any issue related to this PR in other repository?** (such …

Ejbca optimize

---

verne-webhooks/package-lock.json
verne-webhooks/package.json
verne-webhooks/routes/verneRoute.ts

added extra key to messenger publish

---

verne-webhooks/src/app.ts

fix dojot-module dependency

---

redisinit/config_locust.sh
redisinit/create_and_export_cert.sh

Automation scripts for certificate file creation and their transmission to locust hosts 

Automation scripts

---

locust/mqtt_client.py

Corrects some bugs in automation scripts and add "admin:" in the certificate username.

Subscribe to /config topic

---

verne-webhooks/routes/verneRoute.ts

Message payload is passed to Kafka in base64.
Message payload is passe to Kafka as an UTF-8 string.

Decode payload from base64

---

verne-webhooks/routes/verneRoute.ts

Reverts eduardogmisiuk/dojot-verne#53

Revert "Decode payload from base64"

---

vernemq/plugins/dojot_acl_plugin/src/dojot_acl.erl
vernemq/plugins/dojot_acl_plugin/src/dojot_acl_plugin.erl

fix
acl chain error
fixed the chain
no

correcting acl chain

---

README.md
ansible-dojot/roles/vernemq/templates/z_vernemq_cluster.yaml.j2
kubernetes/verne_kube/z_vernemq-cluster.yaml
vernemq/README.md
vernemq/docker-compose.yml
vernemq/scripts_tls/_initVariables.sh
vernemq/scripts_tls/checkBrokerCertHasRevoke.sh
vernemq/vernemq.env
vernemq/vmq_dojot.sh

feat: add check revoke cert from broker

---

ejbca/api-docs/apiary.apib

Adds api docs for ejbca
No api docs
New api doc
no
no

adding api document to ejbca

---

.gitignore
vernemq/plugins/dojot_disconnect_plugin/src/clean_sess.erl

fix disconnect plugin env variable

---

vernemq/build_docker.sh
vernemq/plugins/plugin_builder.sh

feature
manual creation of erlang plugins builds
automatic creation of builds
no
no

add scripts to help create plugins build

---

k2v-bridge/package-lock.json
k2v-bridge/package.json
k2v-bridge/src/__test__/app.test.js
k2v-bridge/src/app.js

update lib k2v

---

v2k-bridge/package-lock.json
v2k-bridge/package.json
v2k-bridge/src/AgentMessenger.js
v2k-bridge/tests/unit-tests/AgentMessenger.test.js
v2k-bridge/tests/unit-tests/MqttClient.test.js

update lib - v2k

---

ansible-dojot/inventories/example_local/group_vars/dojot-k8s/dojot.yaml
ansible-dojot/roles/data-broker/templates/data_broker_deployment.yaml.j2
ansible-dojot/roles/k2v-bridge/templates/k2v_bridge_cluster.yaml.j2
ansible-dojot/roles/kafka/defaults/main.yaml
ansible-dojot/roles/pub-kafka-prometheus/templates/pub-kafka-prometheus.yaml.j2
ansible-dojot/roles/v2k-bridge/templates/v2k_bridge_cluster.yaml.j2
ansible-dojot/roles/vernemq/templates/z_vernemq_cluster.yaml.j2

fix: ansible cluster size kafka
